from app.modules.core.enums.profiles_enum import ESysProfilSuperUserRoleFlag, ESysProfileFlag
from app.modules.core.enums.api_consumers import EApiConsumerFlag
from app.modules.core.models.mapping_keys import CollectionKey


SYSTEM_CONFIG_PERMISSION_RBAC_TITLE_DB = [
    {
        'flag': "checking_core_access",
        "label": "Vérification d'accès sur core",
        "core_seeds": {
            "restricted_profil_list": [
                {
                    "flag": ESysProfileFlag.SYSTEM_PROFIL.value,
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                },
                {
                    "flag": ESysProfileFlag.TEST_SYS_PROFIL.value,
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                },
            ],
            "restricted_api_consumer_list": [
                {
                    "flag": EApiConsumerFlag.SENAT_DIGIT_ADMIN_WEB.value,
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                }
            ],
            "rbac_roles_list": [
                {
                    "flag": ESysProfilSuperUserRoleFlag.SYSTEM_PROFIL_SUPER_ADMIN.value,
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                },
                {
                    "flag": ESysProfilSuperUserRoleFlag.TEST_PROFIL_SUPER_ADMIN.value,
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                },
            ],
            "sys_apps_list": [
                # {
                #     "flag": "system_settings",
                #     "is_link_activated": True,
                #     "is_link_hidden": False,
                #     "is_link_locked": False,
                #     "is_link_deleted": False,
                # }
            ],
            "sys_menus_list": [
                {
                    "flag": "system_settings",
                    "is_link_activated": True,
                    "is_link_hidden": False,
                    "is_link_locked": False,
                    "is_link_deleted": False,
                },
            ],
            "rbac_standalone_actions_obj": {
                "action_to_menus": [],
                "action_to_apps": []
            },
            "rbac_custom_actions_obj": {
                "action_to_menus": [],
                "action_to_apps": []
            },
            "rbac_collection_meta_data_obj": {
                "collection_meta_data_to_menus": {
                    "fetch_url": [
                        {
                            "hard_code_flag": "get_patch_application_permission_target_url",
                            "rbac_endpoint": "/api/v1/cores/patch/applications/permissiontarget",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_menu_permission_target_url",
                            "rbac_endpoint": "/api/v1/cores/patch/menus/permissiontarget",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_application_api_consumer_url",
                            "rbac_endpoint": "/api/v1/cores/patch/applications/apiconsumer",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        
                        {
                            "hard_code_flag": "get_patch_application_system_profil_url",
                            "rbac_endpoint": "/api/v1/cores/patch/applications/systemprofil",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_menu_api_consumer_url",
                            "rbac_endpoint": "/api/v1/cores/patch/menus/apiconsumer",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_menu_system_profil_url",
                            "rbac_endpoint": "/api/v1/cores/patch/menus/systemprofil",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_permission_target_system_profil_url",
                            "rbac_endpoint": "/api/v1/cores/patch/permissionTargets/systemprofiltarget",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_patch_permission_target_api_consumer_url",
                            "rbac_endpoint": "/api/v1/cores/patch/permissionTargets/apiconsumertarget",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_check_core_access_url",
                            "rbac_endpoint": "/api/v1/cores/check-core-access",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # START SUDO ACTION
                        {
                            "hard_code_flag": "get_fetch_one_sudo_action_url",
                            "rbac_endpoint": f"/api/v1/generic/fetch-one/{CollectionKey.RBAC_SUDO_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_upsert_sudo_action_url",
                            "rbac_endpoint": f"/api/v1/generic/upsert/{CollectionKey.RBAC_SUDO_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END SUDO ACTION
                        {
                            "hard_code_flag": "get_config_rbac_actions_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-rbac-actions",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_simplified_config_permissions_url",
                            "rbac_endpoint": "/api/v1/cores/get-simplified-config-permissions",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_config_data_display_type_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-data-display-type",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_config_standalone_menu_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-standalone-menu",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_simplified_config_applications_url",
                            "rbac_endpoint": "/api/v1/cores/get-simplified-config-applications",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_config_path_guards_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-path-guards",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_simplified_config_application_menus_url",
                            "rbac_endpoint": "/api/v1/cores/get-simplified-config-application-menus",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_simplified_config_sub_permissions_url",
                            "rbac_endpoint": "/api/v1/cores/get-simplified-config-sub-permissions",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_simplified_config_sub_endpoints_url",
                            "rbac_endpoint": "/api/v1/cores/get-simplified-config-sub-endpoints",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_api_consumer_profiles_url",
                            "rbac_endpoint": "/api/v1/static/data/get-api-consumer-profiles",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_config_roles_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-roles",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_config_children_display_type_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-children-display-type",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # START PERMISISONS
                        {
                            "hard_code_flag": "get_update_head_permission_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.RBAC_PERMISSION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_rbac_permission_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_PERMISSION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_permission_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.RBAC_PERMISSION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_permission_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.RBAC_PERMISSION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_permission_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.RBAC_PERMISSION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END PERMISSIONS

                        # START RBAC TITLES
                        {
                            "hard_code_flag": "get_head_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_child_head_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/child-head/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_rbac_title_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.RBAC_TITLE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END RBAC TITLES
                        
                        # START RBAC ENDPOINTS
                        {
                            "hard_code_flag": "get_data_overview_endpoints_url",
                            "rbac_endpoint": f"/api/v1/generic/data-overview/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_rbac_endpoint_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_endpoint_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_endpoint_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_endpoint_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_endpoint_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.RBAC_ENDPOINT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END RBAC ENDPOINTS 

                        # START COLLECTION META DATA
                        {
                            "hard_code_flag": "get_config_collection_meta_data_url",
                            "rbac_endpoint": "/api/v1/cores/get-config-collection-meta-data",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_ref_collection_crud_infos_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.REF_COLLECTION_CRUD_INFO.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_ref_collection_crud_infos_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.REF_COLLECTION_CRUD_INFO.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_ref_collection_crud_infos_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.REF_COLLECTION_CRUD_INFO.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_ref_collection_crud_infos_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.REF_COLLECTION_CRUD_INFO.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END COLLECTION META DATA

                        # START DATA DISPLAY TYPE
                        {
                            "hard_code_flag": "get_custom_config_data_display_type_url",
                            "rbac_endpoint": "/api/v1/cores/get-custom-config-data-display-type",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_cfg_data_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.CFG_DATA_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_cfg_data_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.CFG_DATA_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_cfg_data_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.CFG_DATA_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_cfg_data_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.CFG_DATA_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_cfg_data_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.CFG_DATA_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END DATA DISPLAY TYPE

                        # START CHILDREN DISPLAY TYPE
                        {
                            "hard_code_flag": "get_custom_config_children_display_type_url",
                            "rbac_endpoint": "/api/v1/cores/get-custom-config-children-display-type",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_cfg_children_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.CFG_CHILDREN_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_cfg_children_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.CFG_CHILDREN_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_cfg_children_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.CFG_CHILDREN_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_cfg_children_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.CFG_CHILDREN_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_cfg_children_display_type_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.CFG_CHILDREN_DISPLAY_TYPE.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END CHILDREN DISPLAY TYPE


                        # START ACTIONS
                        {
                            "hard_code_flag": "get_custom_config_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_cfg_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_cfg_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_cfg_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_cfg_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_cfg_actions_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.RBAC_ACTION.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END ACTIONS

                        # START COMPONENTS
                        {
                            "hard_code_flag": "get_custom_config_components_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_head_cfg_components_url",
                            "rbac_endpoint": f"/api/v1/generic/head/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_head_cfg_components_url",
                            "rbac_endpoint": f"/api/v1/generic/update-head/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_update_cfg_components_url",
                            "rbac_endpoint": f"/api/v1/generic/update/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_hard_delete_cfg_components_url",
                            "rbac_endpoint": f"/api/v1/generic/hard-delete/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        {
                            "hard_code_flag": "get_add_cfg_components_url",
                            "rbac_endpoint": f"/api/v1/generic/add/{CollectionKey.RBAC_COMPONENT.value}",
                            "is_sudo_action": False,
                            "is_sudo_group_action": False,
                            "menu_flag": "system_settings",
                            "is_parent_field_name": False,
                            "is_link_deleted": False,
                        },
                        # END COMPONENTS

                    ],
                },

            }
        }
    }
]
